[tool.poetry]
name = "python-mlb-statsapi"
version = "0.7.2"
description = "mlbstatsapi python wrapper"
authors = [
    "Matthew Spah <spahmatthew@gmail.com>",
    "Kristian Nilssen <krinilssen@gmail.com>",
]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/zero-sum-seattle/python-mlb-statsapi"
repository = "https://github.com/zero-sum-seattle/python-mlb-statsapi"
packages = [{ include = "mlbstatsapi" }]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/zero-sum-seattle/python-mlb-statsapi/issues"

[tool.poetry.dependencies]
python = ">=3.10"
requests = ">=2"
pydantic = "^2.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.0"
requests-mock = "^1.10.0"
build = "^1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
