name: Report push request url

on:
  pull_request:
    types: [opened]

jobs:
  reportPR:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade slack_sdk          
      - name: Report PR url
        env: 
          PR_URL: ${{ github.event.pull_request.html_url }}
          PR_USER: ${{ github.event.pull_request.user.login }}
          PR_USER_IMAGE: ${{ github.event.pull_request.user.avatar_url }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_TIME: ${{ github.event.pull_request.created_at }}
          PR_BODY: ${{ github.event.pull_request.body }}
          PR_REPO: ${{ github.event.repository.full_name }}
          PR_REPO_URL: ${{ github.event.repository.html_url }}
          NUM_COMMIT: ${{ github.event.pull_request.commits }}
          HEAD_REPO_NAME: ${{ github.event.pull_request.head.ref }}
          BASE_REPO_NAME: ${{ github.event.pull_request.base.ref }}

        run: |
          python3 ./.github/scripts/prslackbot.py ${{ secrets.PR_CHANNEL }} ${{ secrets.SLACK_WEBCLIENT_TOKEN }}
